### ISSUE TITLE
Get and Put step parameters aren't expanded during the across polyfill

### ISSUE THREAD

**Issue by DecentM** [DecentM/concourse-ts#417]
Given this step as the input for the `across-polyfill` transform, it fails to expand variables inside the on_success step.

<details>
  <summary><strong>Source yaml</strong> (Click to expand)</summary>

```yaml
on_success:
  timeout: 6h
  do:
    - attempts: 2
      timeout: 2h
      put: docker-hub
      params:
        image: image_node((.:node))-alpine((.:alpine))/image.tar
        version: node((.:node))-alpine((.:alpine))-concourse-ts((.:npm_concourse-ts-version))-concourse-ts-cli((.:npm_concourse-ts-cli-version))-concourse-ts-recipe-auto-pipeline((.:npm_concourse-ts-recipe-auto-pipeline-version))-concourse-ts-task-oci-build((.:npm_concourse-ts-task-oci-build-version))-typescript((.:npm_typescript-version))
timeout: 6h
across:
  - var: node
    values:
      - 20.2.0
      - 18.16.1
  - var: alpine
    values:
      - "3.18"
task: build-cli_node-((.:node))
config:
  image_resource:
    type: registry-image
    source:
      repository: concourse/oci-build-task
      tag: latest
  platform: linux
  run:
    path: /usr/bin/build
    args: []
  caches:
    - path: cache
  inputs:
    - name: git
  outputs:
    - name: image
  params:
    CONTEXT: git
    OUTPUT_OCI: "true"
    DOCKERFILE: git/Dockerfile.cli
    IMAGE_PLATFORM: linux/amd64
    BUILD_ARG_BASE_IMAGE: node:((.:node))-alpine((.:alpine))
    BUILD_ARG_CLI_VERSION: ((.:npm_concourse-ts-cli-version))
    BUILD_ARG_CONCOURSE_TS_VERSION: ((.:npm_concourse-ts-version))
    BUILD_ARG_AUTO_PIPELINE_VERSION: ((.:npm_concourse-ts-recipe-auto-pipeline-version))
    BUILD_ARG_OCI_BUILD_VERSION: ((.:npm_concourse-ts-task-oci-build-version))
    BUILD_ARG_TYPESCRIPT_VERSION: ((.:npm_typescript-version))
privileged: true
output_mapping:
  image: image_node((.:node))-alpine((.:alpine))
max_in_flight: 1
```
</details>

The output will fail to run because `((.:node))` remains as-is in embedded steps.

<details>
  <summary><strong>Result yaml</strong> (Click to expand)</summary>

```yaml
in_parallel:
  fail_fast: false
  limit: 1
  steps:
    - on_success:
        timeout: 6h
        do:
          - attempts: 2
            timeout: 2h
            put: docker-hub
            params:
              image: image_node((.:node))-alpine((.:alpine))/image.tar
              version: node((.:node))-alpine((.:alpine))-concourse-ts((.:npm_concourse-ts-version))-concourse-ts-cli((.:npm_concourse-ts-cli-version))-concourse-ts-recipe-auto-pipeline((.:npm_concourse-ts-recipe-auto-pipeline-version))-concourse-ts-task-oci-build((.:npm_concourse-ts-task-oci-build-version))-typescript((.:npm_typescript-version))
      timeout: 6h
      task: build-cli_node-20.2.0
      config:
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        platform: linux
        run:
          path: /usr/bin/build
          args: []
        caches:
          - path: cache
        inputs:
          - name: git
        outputs:
          - name: image
        params:
          CONTEXT: git
          OUTPUT_OCI: "true"
          DOCKERFILE: git/Dockerfile.cli
          IMAGE_PLATFORM: linux/amd64
          BUILD_ARG_BASE_IMAGE: node:((build-cli_step_2_across_0:node))-alpine((build-cli_step_2_across_0:alpine))
          BUILD_ARG_CLI_VERSION: ((.:npm_concourse-ts-cli-version))
          BUILD_ARG_CONCOURSE_TS_VERSION: ((.:npm_concourse-ts-version))
          BUILD_ARG_AUTO_PIPELINE_VERSION: ((.:npm_concourse-ts-recipe-auto-pipeline-version))
          BUILD_ARG_OCI_BUILD_VERSION: ((.:npm_concourse-ts-task-oci-build-version))
          BUILD_ARG_TYPESCRIPT_VERSION: ((.:npm_typescript-version))
      privileged: true
      output_mapping:
        image: image_node((.:node))-alpine((.:alpine))
    - on_success:
        timeout: 6h
        do:
          - attempts: 2
            timeout: 2h
            put: docker-hub
            params:
              image: image_node((.:node))-alpine((.:alpine))/image.tar
              version: node((.:node))-alpine((.:alpine))-concourse-ts((.:npm_concourse-ts-version))-concourse-ts-cli((.:npm_concourse-ts-cli-version))-concourse-ts-recipe-auto-pipeline((.:npm_concourse-ts-recipe-auto-pipeline-version))-concourse-ts-task-oci-build((.:npm_concourse-ts-task-oci-build-version))-typescript((.:npm_typescript-version))
      timeout: 6h
      task: build-cli_node-18.16.1
      config:
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        platform: linux
        run:
          path: /usr/bin/build
          args: []
        caches:
          - path: cache
        inputs:
          - name: git
        outputs:
          - name: image
        params:
          CONTEXT: git
          OUTPUT_OCI: "true"
          DOCKERFILE: git/Dockerfile.cli
          IMAGE_PLATFORM: linux/amd64
          BUILD_ARG_BASE_IMAGE: node:((build-cli_step_2_across_1:node))-alpine((build-cli_step_2_across_1:alpine))
          BUILD_ARG_CLI_VERSION: ((.:npm_concourse-ts-cli-version))
          BUILD_ARG_CONCOURSE_TS_VERSION: ((.:npm_concourse-ts-version))
          BUILD_ARG_AUTO_PIPELINE_VERSION: ((.:npm_concourse-ts-recipe-auto-pipeline-version))
          BUILD_ARG_OCI_BUILD_VERSION: ((.:npm_concourse-ts-task-oci-build-version))
          BUILD_ARG_TYPESCRIPT_VERSION: ((.:npm_typescript-version))
      privileged: true
      output_mapping:
        image: image_node((.:node))-alpine((.:alpine))
max_in_flight: 1
```

</details>

Expected output:

```yaml
in_parallel:
  fail_fast: false
  limit: 1
  steps:
    - on_success:
        timeout: 6h
        do:
          - attempts: 2
            timeout: 2h
            put: docker-hub
            params:
              image: image_node((build-cli_step_1_across_1:node))-alpine((build-cli_step_1_across_1:alpine))/image.tar
              version: node((build-cli_step_1_across_1:node))-alpine((build-cli_step_1_across_1:alpine))- # ... etc
# ... etc
```
